name: ci

on:
  push:
    branches:
      - custom

jobs:
  docker:
    strategy:
      matrix:
        cuda_compute: ["7.5", "8.0", "8.6"] # 7.5 for T4, 8.0 for A100, 8.6 for A2, 8.9 for L4/L40S, 9.0 for H100
        cuda_version: ["12.3"] # 12.3 for driver >=525.60.13

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/shield-9/gpu-burn
          tags: |
            cc${{ matrix.cuda_compute }}-cuda${{ matrix.cuda_version }}
            cc${{ matrix.cuda_compute }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

