name: ci

on:
  push:
    branches:
      - custom

jobs:
  build-and-push:
    strategy:
      matrix:
        cuda_version: ["12.2.2", "12.3.1", "12.4.1"] # 12.2.2 for >=535.104.05, 12.3.1 for >=545.23.08, 12.4.1 for >=550.54.15
        # https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id5

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/shield-9/gpu-burn
          tags: |
            cuda${{ matrix.cuda_version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          file: Dockerfile.universal
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CUDA_VERSION=${{ matrix.cuda_version }}

